name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test -project Package.swift -scheme GameUtils -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8,OS=14.4"
